[versions]
agp = "8.3.2"
kotlin = "1.9.0"
coreKtx = "1.13.0"
lifecycleRuntimeKtx = "2.7.0"
appCompat = "1.6.1"
meterial = "1.11.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-meterial = { group = "com.google.android.material", name = "material", version.ref = "meterial" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }